### ISSUE TITLE
Where should I put helper functions?

### ISSUE THREAD

**Issue by GregLancaster71** [DevinVinson/WordPress-Plugin-Boilerplate#275]
I see this template is all OOP.  But I don't see a place provided to place helper functions.  If I am using this for say a review plugin - and I have a function that generates the markup for the rating stars.  That function is called in the admin area as well as the front end. It makes more sense for this function to be placed outside a class method.  Am I right?

**Comment by pe6o** [comment]
Just entered here to write exactly thesame question with exactly the same example.

So what is the best way to proceed with this problem?

I created a public function in `class Easy_Deals`

and then called it in the plugin tempalte with:

```php
$easy_deals = new Easy_Deals();
$easy_deals->rating_function();
```

But I'm sure that this is not the proper way to do this..

**Comment by DevinVinson** [comment]
There isn't a one-size-fits-all answer here. It depends on how you are setting things up and where you need to have access to the helpers.

This older comment/discussion highlights some options when needing to make functions available publicly: https://github.com/DevinVinson/WordPress-Plugin-Boilerplate/issues/218 . The comments might help guide you a bit depending on what your needs are.

For the review plugin, you could put the stars content into a partial in the public/partials folder so that you can include it when needed.
