### ISSUE TITLE
RE: Proper way of enqueue_scripts()

### ISSUE THREAD

**Issue by devcon7** [DevinVinson/WordPress-Plugin-Boilerplate#309]
So, I see that the include/class-plugin-name.php runs: private function define_public_hooks()
to call enqueue_scripts() in public/class-plugin-name-public.php.

I have external js file to load on the front-end and created a folder public/libraries/js to store a jquery and a jquery ui:

wp_enqueue_script( $this->plugin_name, plugin_dir_url( __FILE__ ) . 'libraries/js/jquery-1.10.2.js', array( 'jquery' ), $this->version, false );
wp_enqueue_script( $this->plugin_name, plugin_dir_url( __FILE__ ) . 'libraries/js/jquery-ui.js', array( 'jquery' ), $this->version, false );

Am I doing this right? I am wondering how I can enqueue the default jquery and jquery-ui wordpress contains. 

Do I also have to register script before enqueue them? the function seems different than the wordpress default.

I am also putting the following css:
wp_enqueue_style( $this->plugin_name, plugin_dir_url( __FILE__ ) . 'libraries/css/jquery-ui.css', array(), $this->version, 'all' );

in the public/class-plugin-name-public.php under public function enqueue_styles().

Please advise.

**Comment by slushman** [comment]
First, you don't need to enqueue jQuery since WordPress already enqueues it. If your script is dependent on jQuery, just list it in the dependencies array (like your second script does). You'd do the same of jQuery-UI. See the "Handle" column on this page for the terms to use in that dependencies array:

https://codex.wordpress.org/Function_Reference/wp_enqueue_script

Beyond jQuery and jQuery-UI, you'll want to add something to the $this->plugin_name bit to uniquely ID your script from others. Something like $this->plugin_name . 'script-name' is how I usually do it.

Enqueue registers and enqueues the script/style so there's no real advantage to doing both. This is the WordPress default.

That should be the right way to do the jQuery-UI style, but add the unique ID like I showed above to make sure WordPress doesn't get this confused with another style.

**Comment by AlchemyUnited** [comment]
re: "Enqueue registers and enqueues the script/style so there's no real advantage to doing both. This is the WordPress default."

actually, fwiw, i think it helps to do both. i think - but don't hold me to it :) - that when you do, it makes it easier for someone else - read: perhaps outside the plugin - to unenque something. that is, its (slightly?) easier to unreg than it is to unenq.

i used to think the same but then came across a situation - the details of which i have since forgotten - where reg + enq made more sense (regardless of what the codex implies). i've been on that pattern sense. 

also, in a more bespoke sense, i'm moving to an approach where more common stuff is centralized in a mu-plugin plugin / library. while i haven't done it yet, i am going to eventually have a class that registers any / all scripts and then i can just lean on that, much in the same way WP already pre-registers scripts (e.g., jQuery, etc). again, this is a bespoke approach and doesn't necessarily apply to work let loose in the wild.

**Comment by devcon7** [comment]
Got it down!!

Thank you slushman and AlchemyUnited.

**Comment by AlchemyUnited** [comment]
for anyone interested in an alt-take on enque'ing. this is what i use:

https://github.com/WPezClasses/ezcore/blob/master/class-wp-ezclasses-ezcore-wp-enqueue/class-wp-ezclasses-ezcore-wp-enqueue.php

my "input" is an array of stuff to enqueue. that is, i define what i wanted enque'd and this class is the code that take that data and makes the magic happen. 

again, this ties back to my mention of having a library of common scripts and stuff...
