### ISSUE TITLE
Super swag development environment

### ISSUE THREAD

**Issue by jamrizzi** [DevinVinson/WordPress-Plugin-Boilerplate#425]
Would a development environment, similar to the one found at https://github.com/jamrizzi/wp-plugin-devkit, be worth implementing in the WordPress Plugin Boilerplate?

**Comment by FiGOBLAC** [comment]
Not really,  because then you would have a boilerplate that is opinionated about the tools you use which  then becomes less of a boilerplate imo. Not every developer uses the same tools so its better to have a boilerplate that  keeps it simple and makes it easy for you to make changes that will fit into your own personal setup rather than having to rip out what another developer believes are the best tools to use.

**Comment by jamrizzi** [comment]
Makes sense
