### ISSUE TITLE
How can i pass args to callback add_action

### ISSUE THREAD

**Issue by dankkomcg** [DevinVinson/WordPress-Plugin-Boilerplate#462]
I don't understand how can i pass args to a callback function, based on class admin method.
On `define_admin_hooks()`:

`$this-loader('wp_action', new PluginAdmin(...), 'callback_method', 10, 3)`

I want to pass three args to callback_method because i define this method with three args.
The first is the name of the plugin file. This a internal work on WordPress, but this, how can i pass another three args when i define the hook (over the abstraction for loader class).

Thanks.

**Comment by jonathanbossenger** [comment]
@dankkomcg I'm not to sure what you're asking here, are you able to post a code sample of what you are trying to achieve?

**Comment by dankkomcg** [comment]
@jonathanbossenger sure! 

I want to pass args to my callback function on the hook definition.

`class-plugin-name.php`:
```
private function define_admin_hooks() {

		$plugin_admin = new APluginAdminName(
			$this->get_plugin_name(),
			$this->get_version()
		);

		$this->loader->add_action(
			'admin_enqueue_scripts', // wp action
			$plugin_admin, // instanceof admin class
			'some_method', // method callback from instance of admin class
			10, // default priority
			2 // number of args
		);

}
```

On `admin/APluginAdminName.php`:

```
public function __construct(...){...}
...
public function some_method(String $arg1, String $arg2) {
...
}
```

On this example, when i define a new admin hook, how can i pass args to `APluginAdminName.sometMethod`?

Thanks.

**Comment by slushman** [comment]
You would set those arguments up in the do_action call. Something like:

`$arg1 = 'somestring';
$arg2 = 'anotherstring';
do_action( 'wp_action_forsomething', $arg1, $arg2 );`

Then when you define the hook, tell the callback function there are two arguments:

`$this->loader->add_action(
	'wp_action_forsomething', // wp action
	$plugin_admin, // instance of admin class
	'some_method', // method callback from instance of admin class
	10, // default priority
	2 // args accepted by callback
);`

And then the callback has two parameters:

`public function some_method( $arg1, $arg2) {
...
}`

Doing this outside the boilerplate is almost exactly the same thing. You wouldn't use the loader class (since that's part of the boilerplate) and the class instance is passed in an array in the second argument, not a separate argument:

`add_action(
	'wp_action_forsomething', // wp action
	array( 
		$plugin_admin, // instance of admin class
		'some_method' // method callback from instance of admin class
	), 
	10, // default priority
	2 // args accepted by callback
);`

If the do_action hook does not already have the arguments you are trying to pass, then you'd need to find another way to get that information to your function, like a global or constant. \

In your original post you said that you want the plugin file name as an argument. I usually make the root plugin file name a constant in the root plugin file and call that where I need it:

In the my_plugin.php file:
`define( MY_PLUGIN_FILE_NAME, 'my_plugin' );`

Some class within the plugin:

`public function some_method() {
... // use the MY_PLUGIN_FILE_NAME constant where appropriate in your code.
}`

**Comment by dankkomcg** [comment]
@slushman you give me some ideas to resolve this, thank you, but i have any dudes which wp documentation doesn't resolved for me. For example, when i do a `do_action( 'wp_action_forsomething', $arg1, $arg2 ); `, is it instant executed? or simply does it save args for the event and those will be used when the event for the hook is created?

**Comment by slushman** [comment]
The do_action (and any functions you've hooked there) will run when that do_action happens in the code, not immediately. The variables are able to be passed to those functions. Does that answer your question?

**Comment by dankkomcg** [comment]
@slushman yes, thank you.
