### ISSUE TITLE
Can I use this boilerplate? Is this project still alive?

### ISSUE THREAD

**Issue by AndrejGorodnij** [DevinVinson/WordPress-Plugin-Boilerplate#588]
Does it safe and right use 8 years old boilerplate for realworld projects?

**Comment by seraphyn** [comment]
IMO, look at the issues.
Seems like pretty dead.

**Comment by FreedomRings** [comment]
There are 45 active pull requests but the most recent merge I see was Nov 2017 - I may be missing something.   I used it a while back and it needed tweaking (I can't remember what I had to do) but it worked well enough for a starting place (which is what this is).  Since then I have made my own for our internal use.  Evidently 2.2K others have forked this for their own tweaks.  I think that if you are interested in using it, fork it, glance at the pull requests, and try it out by having it basically do nothing much on a staging site and tweak as needed to make it run before dedicating your business logic to it.
